# Generated by Django 4.2.2 on 2023-07-10 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_alter_dark_text_value_alter_education_degree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.TextField(max_length=30),
        ),
    ]
