# Generated by Django 4.2.2 on 2023-07-11 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_alter_person_first_name_alter_person_last_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dark_text',
            new_name='DarkText',
        ),
        migrations.RenameModel(
            old_name='My_Expertise',
            new_name='MyExpertise',
        ),
        migrations.RenameModel(
            old_name='Personal_info',
            new_name='PersonalInfo',
        ),
        migrations.RenameModel(
            old_name='Who_am_I',
            new_name='WhoAmI',
        ),
    ]
