# Generated by Django 4.2.2 on 2023-07-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_rename_dark_text_darktext_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField()),
            ],
        ),
    ]
