# Generated by Django 4.2.2 on 2023-07-13 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_myexpertise_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myexpertise',
            name='avatar',
            field=models.ImageField(default='avatar.jpg', upload_to=''),
        ),
    ]
