# Generated by Django 4.2.2 on 2023-07-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_alter_myexpertise_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myexpertise',
            name='avatar',
        ),
    ]
